name: 'List Available Apps'
description: 'Dynamically lists all available apps from configs/apps/*.yaml'

outputs:
  matrix:
    description: "JSON array of available apps"
    value: ${{ steps.set-matrix.outputs.matrix }}
  input_schema:
    description: "Input schema for workflow_dispatch"
    value: ${{ steps.set-input-schema.outputs.schema }}

runs:
  using: "composite"
  steps:
    - id: set-matrix
      shell: bash
      run: |
        apps=$(ls configs/apps/*.yaml | xargs -n 1 basename -s .yaml | jq -R -s -c 'split("\n")[:-1]')
        echo "matrix=$apps" >> $GITHUB_OUTPUT
        
    - id: set-input-schema
      shell: bash
      run: |
        schema=$(ls configs/apps/*.yaml | xargs -n 1 basename -s .yaml | jq -R -s -c 'split("\n")[:-1]' | jq -c '{
          type: "object",
          properties: (
            . | map({
              (.): {
                type: "boolean",
                description: "Build \(.)",
                required: false,
                default: false
              }
            }) | add
          )
        }')
        echo "schema=${schema}" >> $GITHUB_OUTPUT 