# YouTube ReVanced Configuration
name: "YouTube"
package: "com.google.android.youtube"

# APK source configuration
source:
  org: google-inc
  repo: youtube
  args: ["--type", "bundle"]  # Download split APK for maximum compatibility

# Build settings
build:
  sdk: { min: 23, target: 33 }
  optimize:
    arch: ["arm64-v8a", "armeabi-v7a"]  # Keep only these architectures
    dpi: ["480dpi", "320dpi"]           # Keep only these DPIs
  version_track: true

# Patch configuration
patches:
  source: "https://github.com/anddea/revanced-patches/releases/latest"
  # Explicitly specify patches to include, empty means use all available
  include: []
  # Always exclude these patches
  exclude: ["GmsCore support"] 