# YouTube ReVanced Configuration
name: "YouTube"
package: "com.google.android.youtube"

# APK source configuration
source:
  org: google-inc
  repo: youtube
  type: bundle  # Download split APK for maximum compatibility

# Patch configuration
patches:
  source: "https://github.com/anddea/revanced-patches/releases/latest"
  # Explicitly specify patches to include, empty means use all available
  include: []
  # Always exclude these patches
  exclude: ["GmsCore support"] 