org: google-inc
repo: youtube
patches:
  source: "https://github.com/anddea/revanced-patches/releases/latest"
  include: 
    - "MaterialYou"
    - "PremiumHeading"
    - "HideAds"
  exclude:
    - "GmsCore support"
arch: arm64-v8a
dpi: 480dpi
apkmd_args:
  - "--type"
  - "bundle"
root_install:
  enabled: true
  device: "device-name"  # From adb devices
  flags:
    - "--mount"
    - "--rip-lib=x86"
    - "--rip-lib=x86_64" 