name: Releasing APK files
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        **Change logs** :point_down:
        
        ## ReVanced Projects
        - [ReVanced](https://github.com/revanced/revanced-patches/releases)
        - [ReVanced Extended (anddea)](https://github.com/anddea/revanced-patches/releases)
        - [ReVanced Experiments](https://github.com/Aunali321/ReVancedExperiments/releases)
        
        ## Other Projects
        - [Twitter Piko](https://github.com/crimera/piko/releases)
        "> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk
        name: ReVanced Collection
        tag: all
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
