name: Releasing APK files
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        **Change log** :point_down:
        [Revanced Beta](https://github.com/revanced/revanced-patches/releases)
        [Revanced Extended anddea Beta](https://github.com/anddea/revanced-patches/releases)
        [Twitter Piko Beta](https://github.com/crimera/piko/releases)
        [Revanced Experiments](https://github.com/Aunali321/ReVancedExperiments/releases)
        "> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk
        name: Revanced & Revanced Extended
        tag: all
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
