global:
  output_dir: ./dist
  retention_days: 7
  architectures:
    strip:  # Architectures to remove
      - armeabi-v7a
      - arm64-v8a
      - x86
      - x86_64
    keep: []  # Not currently used but reserved for future
  dpi:
    keep: [480dpi, 320dpi]
  version_check_interval: 86400 # 24h in seconds