name: Check new patch
permissions: write-all
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
    inputs:
      retry_count:
        description: 'Do not change value below'
        required: false
        default: '1'
jobs:
  check:
    name: Check new patch
    runs-on: ubuntu-latest
    env:
      repository: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh
      - name: Check new patch Revanced Beta
        id: check-rv-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh ReVanced/revanced-patches prerelease youtube-beta-revanced.apk
      - name: Check new patch Revanced Extended forked by Anddea Beta Version
        id: check-rve-anddea-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh anddea/revanced-patches prerelease youtube-beta-anddea.apk
      - name: Check new patch Twitter Piko Beta
        id: check-twitter-piko-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh crimera/piko prerelease twitter-beta-piko.apk
      - name: Check new patch Revanced Experiments
        id: check-Revanced-Experiments
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh Aunali321/ReVancedExperiments latest telegram-revanced-experiments.apk
      - name: Keep workflow run
        if: steps.check-gh.outputs.internet_error == '0'
        uses: gautamkrishnar/keepalive-workflow@v1
      - name: Re-run workflow if github connection not stable
        if: always() && steps.check-rv-beta.outcome == 'skipped' && env.retry_count < env.max_retries
        uses: ./.github/actions/re-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          retry_count: ${{ github.event.inputs.retry_count }}
          max_retries: 3
    outputs:
      check_rv_beta: ${{ steps.check-rv-beta.outputs.new_patch }}
      check_rve_anddea_beta: ${{ steps.check-rve-anddea-beta.outputs.new_patch }}
      check_twitter_piko_beta: ${{ steps.check-twitter-piko-beta.outputs.new_patch }}
      check_Revanced_Experiments: ${{ steps.check-Revanced-Experiments.outputs.new_patch }}

  Patch-Revanced-Beta:
    name: Patch Revanced Beta
    needs: check
    if: ${{ needs.check.outputs.check_rv_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Beta"

  Patch-RVE-anddea-beta:
    name: Patch RVX Anddea Beta
    needs: check
    if: ${{ needs.check.outputs.check_rve_anddea_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "RVE-anddea-beta"

  Patch-Twitter-Piko-Beta:
    name: Patch Twitter Piko Beta
    needs: check
    if: ${{ needs.check.outputs.check_twitter_piko_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Twitter Piko Beta"

  Patch-Revanced-Experiments:
    name: Patch Revanced Experiments
    needs: check
    if: ${{ needs.check.outputs.check_Revanced_Experiments == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Experiments"
