name: Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  org_input: ${{ inputs.org }}
  org_event_input: ${{ github.event.inputs.org }}
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which "Revanced" do you want to patch?'
        required: true
        default: 'Revanced'
        type: choice
        options:
          - 'Revanced'
          - 'rve-anddea'
          - 'Twitter Piko Beta'
          - 'Revanced Experiments'
  workflow_call:
    inputs:
      org:
        required: true
        type: string
jobs:
  patch_rv_beta:
    name: Patch Revanced
    if: ${{ github.event.inputs.org == 'Revanced' || inputs.org == 'Revanced' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 1: Google Photos
        # 2: SoundCloud
        # 3: Lightroom
        run: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rvb
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rvb
        if: steps.check-gh-rvb.outputs.internet_error == '0'
        run: bash src/build/Revanced.sh ${{ matrix.run }}
      - name: Releasing APK files
        id: release-rvb
        if: steps.check-gh-rvb.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_rve_anddea:
    name: Patch RVE Anddea Beta version
    if: ${{ github.event.inputs.org == 'rve-anddea' || inputs.org == 'rve-anddea' }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Install library
        run: |
          apt-get update
          apt-get install -y curl jq wget unzip
      - name: Check github connection
        id: check-gh-rve-anddea
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve-anddea
        if: steps.check-gh-rve-anddea.outputs.internet_error == '0'
        run: bash src/build/Anddea-Revanced.sh
      - name: Cache
        uses: actions/upload-artifact@v4
        with:
          name: Cache_anddea_beta
          path: |
            ./release/*.apk
  release_rve_anddea:
    name: Release RVE Anddea Beta
    needs: patch_rve_anddea
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/download-artifact@v4
        with:
          name: Cache_anddea_beta
          path: ./release
      - name: Releasing APK files
        uses: ./.github/actions/release
  patch_twitter_piko_beta:
    name: Patch Twitter Piko Beta
    if: ${{ github.event.inputs.org == 'Twitter Piko Beta' || inputs.org == 'Twitter Piko Beta' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-piko-beta
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-piko-beta
        if: steps.check-gh-piko-beta.outputs.internet_error == '0'
        run: bash src/build/Piko.sh prerelease
      - name: Releasing APK files
        id: release-piko-beta
        if: steps.check-gh-piko-beta.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_rv_experiments:
    name: Patch Revanced Experiments
    if: ${{ github.event.inputs.org == 'Revanced Experiments' || inputs.org == 'Revanced Experiments' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rv-experiments
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rv-experiments
        if: steps.check-gh-rv-experiments.outputs.internet_error == '0'
        run: bash src/build/Revanced-Experiment.sh
      - name: Releasing APK files
        id: release-rv-experiments
        if: steps.check-gh-rv-experiments.outputs.internet_error == '0'
        uses: ./.github/actions/release
